version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - go get github.com/aws/aws-lambda-go/events
      - go get github.com/aws/aws-lambda-go/lambda

  build:
    commands:
      # Build our go application
      - cd webapp/src/coffee
      - go build -o main
      - cd ../../

      # Package our application with AWS SAM
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file template-export-get.json
      - cd ..
artifacts:
  type: zip
  files:
    - template-export-get.json
