version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - go get github.com/aws/aws-lambda-go/events
      - go get github.com/aws/aws-lambda-go/lambda
      - go get github.com/aws/aws-sdk-go/aws
      - go get github.com/aws/aws-sdk-go/aws/session
      - go get github.com/aws/aws-sdk-go/service/dynamodb
      - go get github.com/aws/aws-sdk-go/service/dynamodb/dynamodbattribute

  build:
    commands:
      # Build our go application
      - cd webapp/src/product
      - go build -o main *.go
      - cd ../../..

      # Package our application with AWS SAM
      - aws cloudformation package --template-file webapp/template.yml --s3-bucket ${S3_BUCKET} --output-template-file template-export-get.json
      
artifacts:
  type: zip
  files:
    - template-export-get.json
