version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.13

  build:
    commands:
      # Build our go application
      - go build -o main

      # Package our application with AWS SAM
      - aws cloudformation package --template-file template.yml --s3-bucket ${S3_BUCKET} --output-template-file packaged.yml
artifacts:
  type: zip
  files:
    - template-export-get.json
