AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Deploy Serverless application using API Gateway, Lambda, and DynamoDB'
Globals:
  Function:
    Timeout: 5
    Runtime: go1.x
    Tracing: Active

Resources:
  ProcessProductFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: product/process-product
      Runtime: go1.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MyDynamoDBTable
      Environment:
        Variables:
          TABLE_NAME: !Ref MyDynamoDBTable
          REGION: !Ref 'AWS::Region'
      Events:
        # Products
        GetProductsAPI:
          Type: Api
          Properties:
            Path: /products
            Method: GET
            RestApiId:
              Ref: MyApi
        GetSingleProductsAPI:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: GET
            RestApiId:
              Ref: MyApi
        PostProductsAPI:
          Type: Api
          Properties:
            Path: /products
            Method: POST
            RestApiId:
              Ref: MyApi
        PutProductsAPI:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: PUT
            RestApiId:
              Ref: MyApi
        DeleteProductsAPI:
          Type: Api
          Properties:
            Path: /products/{productId}
            Method: DELETE
            RestApiId:
              Ref: MyApi
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
  
  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName: !Ref 'AWS::StackName'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: 'N'
      KeySchema:
        - AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
   
  
      
Outputs:
  GetCoffeeFunctionApi:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com'
  LambdaFunctionUrl:
    Description: URL for Lambda Get Function
    Value: !Sub >-
      https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${ProcessProductFunction}/aliases/live?tab=configuration
  CodeDeployUrl:
    Description: URL for CodeDeploy Deployments
    Value: !Sub >-
      https://console.aws.amazon.com/codesuite/codedeploy/deployments?region=${AWS::Region}
  DynamoDBUrl:
    Description: URL for DynamoDB CloudProviders table
    Value: !Sub >-
      https://console.aws.amazon.com/dynamodb/home?region=${AWS::Region}#tables:selected=${MyDynamoDBTable};tab=items
