AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Deploy Serverless application using API Gateway, Lambda, and DynamoDB'

Globals:
  Function:
    Timeout: 5
    Runtime: go1.x
    Tracing: Active
Resources: 
  ProcessCoffeeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: coffee/process-coffee
      Runtime: go1.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName:
              Ref: MyDynamoDBTable
      Environment:
        Variables:
          TABLE_NAME:
            Ref: MyDynamoDBTable
          REGION:
            Ref: AWS::Region
      Events:
        GetCoffeeFunctionApi:
          Type: Api
          Properties:
            ApiId:
              Ref: MyApi
            Method: GET
            Path: /coffee
            TimeoutInMillis: 15000
            Method: POST
            Path: /coffee/{id}
            TimeoutInMillis: 15000
      Description: Get data from DynamoDB table
  
    
  MyDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Delete
    Properties:
      TableName:
        Ref: 'AWS::StackName'
      AttributeDefinitions:
        - AttributeName: type
          AttributeType: S
        - AttributeName: id
          AttributeType: 'N'        
       
      KeySchema:
        - AttributeName: type
          KeyType: HASH
        - AttributeName: id
          KeyType: RANGE
        
        
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  
  MyApi:
    Type: 'AWS::Serverless::HttpApi'
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - '*'
  
Outputs:
  GetCoffeeFunctionApi:
    Description: API Gateway endpoint URL
    Value:
      'Fn::Sub': 'https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com'

  LambdaFunctionUrl:
    Description: URL for Lambda Get Function
    Value:
      'Fn::Sub': >-
        https://console.aws.amazon.com/lambda/home?region=${AWS::Region}#/functions/${ProcessCoffeeFunction}/aliases/live?tab=configuration

  CodeDeployUrl:
    Description: URL for CodeDeploy Deployments
    Value:
      'Fn::Sub': >-
        https://console.aws.amazon.com/codesuite/codedeploy/deployments?region=${AWS::Region}
 
  DynamoDBUrl:
    Description: URL for DynamoDB CloudProviders table
    Value:
      'Fn::Sub': >-
        https://console.aws.amazon.com/dynamodb/home?region=${AWS::Region}#tables:selected=${MyDynamoDBTable};tab=items
